#Esta configuração ativa o modo desenvolvimento e inclui uma instalação local de MongoDB
devMode:
  enabled: true


engine:
  #Esta configuração aumenta o limite de upload do NGINX para 5 GB 
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 5000m
      nginx.org/client-max-body-size: 50000m
  #Esta configuração aceita os termos de licenciamento (EULA) do produto
  acceptEULA: "yes"

elastic-infra:
  #Esta configuração aumenta o limite de upload do NGINX para 5 GB
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 50000m
      nginx.org/client-max-body-size: 50000m
  #Configuração específica para o Minikube (não utilize com outros provedores K8S)
  nginx-ingress:
    controller:
      service:
        type: NodePort
        nodePorts:
          https: 32443
      extraArgs.report-node-internal-ip-address: ""
  #Esta configuração aumenta o limite de upload do NGINX para 5 GB
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 50000m
      nginx.org/client-max-body-size: 50000m

hub:
 ingress:
   annotations:
     nginx.ingress.kubernetes.io/auth-signin: https://$host:32443/login?returnto=$request_uri

management-console:
 ingress:
   annotations:
     nginx.ingress.kubernetes.io/auth-signin: https://$host:32443/login?returnto=$request_uri

edge-auth:
  oidc:
    redirectUri: https://elastic.example:32443/login/callback